name: test

on: [push, workflow_dispatch]

jobs:
  rtl_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cocotb + simulators
        run: |
          pip install cocotb pytest junit-xml
          sudo apt-get update
          sudo apt-get install -y iverilog verilator

      - name: Sanity check Python
        run: |
          which python
          python -c "import sys, encodings; print(sys.version); print(encodings.__file__)"

      - name: Run RTL tests with Icarus
        working-directory: test
        env:
          COCOTB_PYTHON: ${{ steps.py.outputs.python-path }}
          PYTHON:        ${{ steps.py.outputs.python-path }}
        run: |
          make clean || true
          SIM=icarus make
          test -f results.xml
          ! grep failure results.xml

      - name: Run RTL tests with Verilator
        working-directory: test
        env:
          COCOTB_PYTHON: ${{ steps.py.outputs.python-path }}
          PYTHON:        ${{ steps.py.outputs.python-path }}
        run: |
          make clean || true
          unset PYTHONHOME PYTHONPATH
          SIM=verilator make
          test -f results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: Upload VCD
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/*.vcd
            test/results.xml
