name: test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator make

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Force python3.11 as default
        run: | 
          sudo rm -f /usr/bin/python3
          sudo ln -s $(which python3.11) /usr/bin/python3
          python3 --version

      - name: Install Python packages
        run: pip install -r test/requirements.txt

      - name: Run cocotb tests (Verilator)
        env:
          PYTHON: python3.11
          COCOTB_PYTHON: python3.11
        run: |
          cd test
          make clean || true
          make SIM=verilator
          test -f results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: Upload simulation results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test/*.vcd
            test/results.xml
            
      - name: Run cocotb tests (Gate-Level, Verilator)
        env:
          PYTHON: python3.11
          COCOTB_PYTHON: python3.11
          PYTHON3: python3.11
        run: |
          cd test
          make -f Makefile.gl clean || true
          make -f Makefile.gl SIM=verilator
          test -f results_gl.xml
          ! grep failure results_gl.xml

      - name: Test Summary (GL)
        uses: test-summary/action@v2.3
        with:
          paths: "test/results_gl.xml"
        if: always()

      - name: Upload simulation results (Gate-Level)
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-gl
          path: |
            test/*.vcd
            test/results_gl.xml