name: test
on: [push, workflow_dispatch]

jobs:
  rtl_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        id: py
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cocotb + Verilator
        run: |
          pip install -r test/requirements.txt
          sudo apt-get update
          sudo apt-get install -y verilator

      - name: Run RTL tests (cocotb + Verilator)
        env:
          COCOTB_PYTHON: ${{ steps.py.outputs.python-path }}   # forza il Python giusto
        run: |
          cd test
          make clean || true
          unset PYTHONHOME PYTHONPATH                           # <-- importantissimo
          SIM=verilator make
          test -f results.xml
          ! grep failure results.xml


      - name: Test Summary (RTL)
        uses: test-summary/action@v2.3
        if: always()
        with:
          paths: test/results.xml

      - name: Upload RTL artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: rtl_test_artifacts
          path: |
            test/tb.vcd
            test/results.xml

  gl_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Questa action:
      # - scarica la netlist gate-level (tt_submission)
      # - la copia in test/gate_level_netlist.v
      # - installa iverilog + cocotb
      # - esegue: cd test && rm tb.vcd results.xml ; make clean ; GATES=yes make
      # - verifica test/results.xml
      - name: Gate-Level Test (TinyTapeout)
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25a

      - name: Test Summary (GL)
        uses: test-summary/action@v2.3
        if: always()
        with:
          paths: test/results.xml

      - name: Upload GL artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: gatelevel_test_vcd
          path: |
            test/tb.vcd
            test/results.xml
